### ISSUE TITLE
Idea: Support Capacitor

### ISSUE THREAD

**Issue by kalicki** [tombolaltd/cordova-plugin-insomnia#1]
Add support for Capacitor

https://capacitor.ionicframework.com/docs/plugins/

**Comment by keithbarrow** [comment]
To be honest we're a Cordova-only shop, so we'd never need this, it'll add an unnecessary overhead for our purposes - we've even ditched support for OSs we don't deploy to in this repo. You could fork our repo, or look at Eddie Verbruggen's original (which has more supported OSs) and fork that: https://www.npmjs.com/package/cordova-plugin-insomnia
